---
- include_tasks: member-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: member-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- name: Deploy Samba Domain Member Server configuration
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: 'testparm -s %s'
    owner: root
    group: root
    mode: '0644'

- name: Deploy Kerberos configuration
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable winbind in /etc/nsswitch.conf
  template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure paths in shares are present   # noqa risky-file-permissions
  file:
    path: '{{ item.path }}'
    state: directory
  with_items: '{{ samba_shares.values() }}'
  when: item.path is defined
  # Note: permissions and ownership are not enforced
